#include<stdio.h>
#include<conio.h>
#include<stdlib.h>
/* #include<limits.h>           //include the files as needed and use this instead of including every single file everytime
#include<time.h>
#include<search.h>
#include<share.h>
#include<values.h>
#include<float.h>
#include<graphics.h>
#include<ctype.h>
#include<process.h>
#include<math.h>
#include<io.h>
#include<share.h>
#include<assert.h>
#include<dir.h>
#include<generic.h>
#include<constrea.h> */