#include<stdio.h>
#include<conio.h>
int main()
{
clrscr();

switch(printf("hello world")){}                       //either one can be used to print                       
                                                      //either one can be used to print                           
//while(!printf("hello world")){}                     //either one can be used to print                           

getch();
return 0;
}