name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello stranger!This is your first issue! feel free to speak your mind! \n yours truly -Hidden"
        pr-message: "Hello! This is your first pull request here, thanks for the pull request! what can be improved? thanks for showing interest, i'll take a look into that! \n yours truly -Hidden"
